FROM localhost/freebsd-nginx-stable:14.3

VOLUME /usr/local/poudriere/data
VOLUME /usr/local/poudriere/data/logs/bulk
VOLUME /usr/local/poudriere/data/packages
VOLUME /usr/local/share/poudriere/html

COPY --chown=0:0 --chmod=0644 nginx.conf /usr/local/etc/nginx/nginx.conf
COPY --chown=0:0 --chmod=0644 poudriere.conf /usr/local/etc/nginx/conf.d/poudriere.conf
RUN  rm -f /usr/local/etc/nginx/conf.d/default.conf

RUN /usr/local/sbin/nginx -t
