FROM {% if registry.name %}{{ registry.name }}/{% endif %}{% if registry.username %}{{ registry.username }}/{% endif %}{% if registry.project %}{{ registry.project }}/{% endif %}nginx:freebsd{{ os_major_version }}.{{ short_os_minor_version }}
FROM ghcr.io/matias-pizarro/freebsd-oci-containers/nginx:freebsd

VOLUME /var/run/podman

COPY --chown=0:0 --chmod=0644 nginx.conf /usr/local/etc/nginx/nginx.conf
COPY --chown=0:0 --chmod=0644 podman_api.conf /usr/local/etc/nginx/conf.d/podman_api.conf
RUN  rm -f /usr/local/etc/nginx/conf.d/default.conf

RUN /usr/local/sbin/nginx -t
