FROM {% if registry.name %}{{ registry.name }}/{% endif %}{% if registry.username %}{{ registry.username }}/{% endif %}{% if registry.project %}{{ registry.project }}/{% endif %}nginx:freebsd{{ os_major_version }}.{{ short_os_minor_version }}

VOLUME /usr/local/poudriere/data
VOLUME /usr/local/poudriere/data/logs/bulk
VOLUME /usr/local/poudriere/data/packages
VOLUME /usr/local/share/poudriere/html

COPY --chown=0:0 --chmod=0644 nginx.conf /usr/local/etc/nginx/nginx.conf
COPY --chown=0:0 --chmod=0644 poudriere.conf /usr/local/etc/nginx/conf.d/poudriere.conf
RUN  rm -f /usr/local/etc/nginx/conf.d/default.conf

RUN /usr/local/sbin/nginx -t
