FROM ghcr.io/freebsd/freebsd-runtime:14.3@sha256:3a5ffe995405b5f6300797b38d87328a267bbeeb550d3707c9c5e0a76827a978
RUN /bin/pkg upgrade -yr FreeBSD-base
RUN /bin/pkg install -yr FreeBSD-base FreeBSD-utilities
