FROM localhost/base-headless-system
ENV NGINX_PORT=80

RUN --network=host env ASSUME_ALWAYS_YES=YES pkg install -r FreeBSD nginx
RUN nginx -t
RUN sysrc nginx_enable="YES"

COPY --chown=0:0 --chmod=0644 nginx-base/files/nginx.conf /usr/local/etc/nginx/nginx.conf
COPY --chown=www:www --chmod=0550 nginx-base/files/run.sh /usr/local/bin/run.sh

EXPOSE ${NGINX_PORT}

CMD ["/usr/local/bin/run.sh"]
