FROM localhost/base-system

RUN --network=host env ASSUME_ALWAYS_YES=YES pkg install -r FreeBSD openssl
RUN --network=host env ASSUME_ALWAYS_YES=YES pkg install -r FreeBSD yarn go gmake

RUN mkdir -p /home/mpizarro/devel/matias-pizarro/pulumi
RUN chown -R 1010:1010 /home/mpizarro/devel
VOLUME /home/mpizarro/devel/matias-pizarro/pulumi

CMD [ "/usr/local/bin/bash" ]
