; ****************************************
; * Global options                       *
; ****************************************

; (Useful for troubleshooting)
;	foreground = yes
;	debug      = info
;	output     = /tmp/stunnel.log

; ****************************************
; * Include configuration file fragments *
; ****************************************

include = /usr/local/etc/stunnel/conf.d
