; pkg0.sjb.freebsd.org: 1.3 MB/s
; pkg0.nyi.freebsd.org: 367.5 kB/s
; pkg0.your.freebsd.org: 323.6 kB/s
; pkg0.tuk.freebsd.org: 240.3 kB/s
; pkg0.pao.freebsd.org: 174.0 kB/s
; pkg0.son.freebsd.org: 159.8 kB/s
; pkg0.bbt.freebsd.org: 100.0 kB/s
; pkg0.kwc.freebsd.org: 97.8 kB/s
; pkg0.bra.freebsd.org: 89.0 kB/s
; pkg0.syd.freebsd.org: 68.1 kB/s
; pkg0.twn.freebsd.org: 0.0 B/s
; pkg0.kul.freebsd.org: 0.0 B/s
; pkg0.jinx.freebsd.org: 0.0 B/s

[pkg.internal]
client      = yes
accept      = 127.0.0.1:8000
connect     = pkg.internal:80
verifyChain = no

[pkg0.sjb.freebsd.org]
client      = yes
accept      = 127.0.0.1:8001
connect     = pkg0.sjb.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.nyi.freebsd.org]
client      = yes
accept      = 127.0.0.1:8002
connect     = pkg0.nyi.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.your.freebsd.org]
client      = yes
accept      = 127.0.0.1:8003
connect     = pkg0.your.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.tuk.freebsd.org]
client      = yes
accept      = 127.0.0.1:8004
connect     = pkg0.tuk.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.pao.freebsd.org]
client      = yes
accept      = 127.0.0.1:8005
connect     = pkg0.pao.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.son.freebsd.org]
client      = yes
accept      = 127.0.0.1:8006
connect     = pkg0.son.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.bbt.freebsd.org]
client      = yes
accept      = 127.0.0.1:8007
connect     = pkg0.bbt.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.kwc.freebsd.org]
client      = yes
accept      = 127.0.0.1:8008
connect     = pkg0.kwc.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.bra.freebsd.org]
client      = yes
accept      = 127.0.0.1:8009
connect     = pkg0.bra.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.syd.freebsd.org]
client      = yes
accept      = 127.0.0.1:8010
connect     = pkg0.syd.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.twn.freebsd.org]
client      = yes
accept      = 127.0.0.1:8011
connect     = pkg0.twn.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.kul.freebsd.org]
client      = yes
accept      = 127.0.0.1:8012
connect     = pkg0.kul.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes

[pkg0.jinx.freebsd.org]
client      = yes
accept      = 127.0.0.1:8013
connect     = pkg0.jinx.freebsd.org:443
verifyChain = yes
CApath      = /etc/ssl/certs
checkHost   = pkg.freebsd.org
OCSPaia     = yes
