FROM docker.io/dougrabson/freebsd14.1-small
MAINTAINER Matias Pizarro <matias@pizarro.net>

VOLUME /var/cache/pkg

RUN --network=host env ASSUME_ALWAYS_YES=YES pkg bootstrap && pkg update

COPY --chown=0:0 --chmod=0550 base-headless-system/files/run.sh /usr/local/bin/run.sh

CMD ["/usr/local/bin/run.sh"]
